### ISSUE TITLE
Split jdocbookStyle Configuration into multiple

### ISSUE THREAD

**Issue by sebersole** [gradle/gradle-jdocbook#3]
Thinking at least 2, maybe 3..

The main thinking here is around XSLT .  Right now there are 2 options to make XSLT available to rendering:
- placing the artifact in buildscript.classpath
- placing the artifact in jdocbookStyle

The second option has the undesirable side affect of polluting the staging directory (and ultimately the publish directory) with unneeded XSLT scripts, dependencies, etc

The possible 3rd is fonts.
- jdocbookStyle
- jdocbookXslt
- jdocbookFont

**Comment by stliu** [comment]
i think this is fine

**Comment by sebersole** [comment]
For now, just added jdocbookXsl.  I think jdocbookFont might make sense, but we are not really using fonts atm to test that
